services:
    frontend:
        build:
            context: ./stretches-site
            target: development
        ports:
            - 9000:9000
        stdin_open: true
        volumes:
            - ./stretches-site:/usr/src/app
            - /usr/src/app/node_modules
        restart: "no"
        networks:
            - react-express
        depends_on:
            - backend

    backend:
        restart: "no"
        build:
            context: ./api
            target: development
        volumes:
            - ./api:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - mongo
        networks:
            - express-mongo
            - react-express
        expose:
            - 9000
    mongo:
        restart: always
        image: mongo:4.2.0
        volumes:
            - ./data:/data/db
        networks:
            - express-mongo
        expose:
            - 27017
networks:
    react-express:
    express-mongo:
