export const mockEmbedUrls = {
    youtubeEmbed: "https://youtu.be/rN89z5LqFH8?si=-sm_D_sFwgwCBFWP",
    spotifyEmbed: ""
}
export const mockTimerSets = [
    {
        _id: "back-flex",
        label: "Back Flexibility",
        timers: [
            {
                time: {
                    seconds: 30,
                    minutes: 0,
                    hours: 0,
                },
                label: "Bow Pose",
                slideImagePath: "/uploads/Back Flexibility/Bow.webp",
                description: "Bow Pose",
                autostart: false,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 2,
                _id: "63d8040ccb6579e3293e8b45",
            },
            {
                time: {
                    seconds: 30,
                    minutes: 0,
                    hours: 0,
                },
                label: "Cat Pose",
                slideImagePath: "/uploads/Back Flexibility/Cat Pose.webp",
                autostart: true,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 2,
                _id: "63d8040ccb6579e3293e8b46",
            },
            {
                time: {
                    seconds: 0,
                    minutes: 1,
                    hours: 0,
                },
                label: "Cobra Pose",
                slideImagePath: "/uploads/Back Flexibility/Cobra-Pose.webp",
                autostart: true,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 0,
                _id: "63d8040ccb6579e3293e8b47",
            },
            {
                time: {
                    hours: 0,
                    seconds: 30,
                    minutes: 0,
                },
                label: "Cow Pose",
                slideImagePath: "/uploads/Back Flexibility/Cow Pose.webp",
                description: "",
                autostart: true,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 1,
                _id: "63d95f69bf5b92fa1b3af174",
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 1,
                },
                label: "Downward Dog",
                slideImagePath: "/uploads/Back Flexibility/Downward-Dog.webp",
                description: "",
                autostart: false,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 0,
                _id: "63d96726bf5b92fa1b3af752",
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 1,
                },
                label: "Low Lunge",
                slideImagePath: "/uploads/Back Flexibility/Low-Lunge.webp",
                autostart: true,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 0,
                _id: "63d9676fbf5b92fa1b3af8ed",
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 1,
                },
                label: "Plow Halasana",
                slideImagePath: "/uploads/Back Flexibility/Plow-Halasana.webp",
                description: "head circle x 20",
                autostart: true,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 0,
                _id: "63d967a2bf5b92fa1b3afaf2",
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 1,
                },
                label: "Wheelpose",
                slideImagePath: "/uploads/Back Flexibility/Wheelpose.webp",
                autostart: true,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 0,
                _id: "63d9682bbf5b92fa1b3afd84",
            },
        ],
        spotifyLink: "",
        repeatNumber: 1,
    },
    {
        _id: "desk-job",
        label: "Desk Job Exercises",
        timers: [
            {
                time: {
                    seconds: 30,
                    minutes: 1,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Bilateral-Scaption.png",
                autostart: false,
                isBreak: true,
                isAutoBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63d81e6cf164a6f75cf9ddf6",
                },
            },
            {
                time: {
                    seconds: 15,
                    minutes: 1,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Bent-Over-Rows.png",
                autostart: false,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63d81e6cf164a6f75cf9ddf8",
                },
            },
            {
                time: {
                    seconds: 0,
                    minutes: 1,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/RaJXKCB.png",
                autostart: false,
                isBreak: false,
                isAutoBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63d81e6df164a6f75cf9ddfa",
                },
            },
        ],
        youtubeLink: "",
        spotifyLink: "",
        repeatNumber: 1,
        __v: 0,
    },
    {
        _id: "hamstring-flex",
        label: "Hamstring Flexibility",
        timers: [
            {
                time: {
                    seconds: 10,
                    minutes: 1,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Arm-Side-Horizontal.png",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63d820d675111c3e9a6d2214",
                },
            },
            {
                time: {
                    seconds: 0,
                    minutes: 1,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Prone-I.png",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63d820d675111c3e9a6d2216",
                },
            },
            {
                time: {
                    seconds: 0,
                    minutes: 1,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Prone-Y.png",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63d820d675111c3e9a6d2218",
                },
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 1,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Prone-W.png",
                description: "",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63ddbb6e6b0b8efa92fb1314",
                },
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 1,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Prone-Superman.png",
                description: "",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63ddbb6e6b0b8efa92fb1315",
                },
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 1,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Prone-T.png",
                description: "",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63ddbb976b0b8efa92fb13a2",
                },
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 2,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Foam Roller Thing.gif",
                description: "2 minutes, hold up for 10",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63ddc465975e3e1ff39b690f",
                },
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 2,
                },
                label: "New Timer",
                slideImagePath: "/uploads/FloorAngelsOnRoll.gif",
                description: "",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: {
                    $oid: "63ddc465975e3e1ff39b6910",
                },
            },
        ],
        youtubeLink: "",
        spotifyLink: "",
        repeatNumber: 1,
    },
    {
        _id: "migraine-relief",
        label: "Migraine Relief Exercises",
        timers: [
            {
                time: {
                    seconds: 30,
                    minutes: 0,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Back Flexibility/Bow.webp",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: "63d82155ed3277e125ebbb76",
            },
            {
                time: {
                    seconds: 0,
                    minutes: 1,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Wall-Push-Ups.png",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: "63d82155ed3277e125ebbb78",
            },
            {
                time: {
                    seconds: 0,
                    minutes: 1,
                    hours: 0,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Wall-Circles.webp",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: "63d82155ed3277e125ebbb7a",
            },
            {
                time: {
                    hours: 0,
                    seconds: 0,
                    minutes: 1,
                },
                label: "New Timer",
                slideImagePath: "/uploads/Wall-Slide-Elastic-Band.png",
                description: "",
                autostart: false,
                isBreak: false,
                repeatNumber: 0,
                _id: "63ddbc0d6b0b8efa92fb1457",
            },
        ],
        youtubeLink: "",
        spotifyLink: "",
        repeatNumber: 1,
        __v: 0,
    },
];
